user www-data;

events
{
    worker_connections 1024;
}

http
{
    include /etc/nginx/mime.types;
    
    server
    {
        listen 80;
        listen [::]:80;
        server_name ${DOMAIN_NAME};
        
        return 301 https://$host$request_uri;  #redirect to https
    }

    server 
    {
		listen 443 ssl;  #IPv4
		listen [::]:443 ssl;  #IPv6
		
		server_name ${DOMAIN_NAME};

		ssl_certificate     /etc/nginx/ssl/tls.crt;
		ssl_certificate_key /etc/nginx/ssl/tls.key;
		ssl_protocols TLSv1.2 TLSv1.3;

		root /var/www/wp;
		index index.php index.html;

		location / 
		{
			try_files $uri $uri/ =404;
		}

		location ~ \.php$
		{
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME /var/www/wp$fastcgi_script_name;
			fastcgi_param PATH_INFO $fastcgi_path_info;
			fastcgi_param HTTPS on;
			fastcgi_split_path_info ^(.+\.php)(/.+)$; 
			try_files $uri =404;
		}
    }
}

