services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: ./.env
    networks:
      - inception-network
    volumes:
      - /home/michoi/data/mariadb:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-P",
          "3306",
          "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 90s

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: ./.env
    networks:
      - inception-network
    volumes:
      - /home/michoi/data/wordpress:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: unless-stopped
    env_file: ./.env
    networks:
      - inception-network
    volumes:
      - /home/michoi/data/wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/html/wp-login.php"]
      interval: 5s
      timeout: 60s
      retries: 10

networks:
  inception-network:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/michoi/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/michoi/data/wordpress
